#!/bin/sh

COMMITTED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

# Execute gofmt
if [ "$COMMITTED_GO_FILES" ]; then
  UN_FORMATTED_FILES=$(echo "$COMMITTED_GO_FILES" | xargs gofmt -l)
  if [ "$UN_FORMATTED_FILES" ]; then
    echo >&2 "Go files must be formatted with gofmt. Please run:"
    echo >&2 "gofmt -w $(echo "$UN_FORMATTED_FILES" | tr '\n' ' ')"
    exit 1
  fi
fi

# Execute goimports
if [ "$COMMITTED_GO_FILES" ]; then
  UN_FORMATTED_FILES=$(echo "$COMMITTED_GO_FILES" | xargs goimports -l)
  if [ "$UN_FORMATTED_FILES" ]; then
    echo >&2 "Go files must be formatted with goimports. Please run:"
    echo >&2 "goimports -w $(echo "$UN_FORMATTED_FILES" | tr '\n' ' ')"
    exit 1
  fi
fi
